// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgM_S8hk6vW-GyyNymeDnPci85M2v6bQs',
    appId: '1:991071408047:web:68a441086ee2c1f3a8a95a',
    messagingSenderId: '991071408047',
    projectId: 'macc-6dcf0',
    authDomain: 'macc-6dcf0.firebaseapp.com',
    storageBucket: 'macc-6dcf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6qa6rn-gx3Nx0UYd1irKC9SUKiSSuys0',
    appId: '1:991071408047:android:9704eb7452ed70eca8a95a',
    messagingSenderId: '991071408047',
    projectId: 'macc-6dcf0',
    storageBucket: 'macc-6dcf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLfseCYPfDvyzpyBCc8aBxDXL7QcGThco',
    appId: '1:991071408047:ios:863dccd6e30ddf74a8a95a',
    messagingSenderId: '991071408047',
    projectId: 'macc-6dcf0',
    storageBucket: 'macc-6dcf0.appspot.com',
    iosClientId: '991071408047-idu3grfietjspeln30m1n0fkoju1110j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuadro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLfseCYPfDvyzpyBCc8aBxDXL7QcGThco',
    appId: '1:991071408047:ios:863dccd6e30ddf74a8a95a',
    messagingSenderId: '991071408047',
    projectId: 'macc-6dcf0',
    storageBucket: 'macc-6dcf0.appspot.com',
    iosClientId: '991071408047-idu3grfietjspeln30m1n0fkoju1110j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuadro',
  );
}
